### ISSUE TITLE
Blazor Server App - Saving Data while logged in as a Tenant fails to save TenantId value in Tenant column - (uniqueidentifier)

### ISSUE THREAD

**Issue by 274188A** [radzenhq/radzen-blazor-studio#100]
>Radzen Blazor Studio 1.6.0
Blazor Server App
MSSQL Server DB

**STEPS**
Logon as Tenant
Create a record.
Check DB for TenantId value in Table.

No value in Table - just NULL.  Other values saved correctly.

**Possible Causes**
The PK and TenantID columns are of type `uniqueidentifier` (guid)

**Comment by akorchev** [comment]
Radzen Blazor Studio will not automatically set the tenantid. You need to update your page to do that.

**Comment by 274188A** [comment]
I don't understand.  When you say "set the tenant id" do you mean set the actual value of the tenant logged in?

My table already has the column there - but surely the code knows who is logged in and what their tenant id is?

**Comment by 274188A** [comment]
I'm not expecting radzen studio to magically create a tenantid column for me.  but the code should be able to set a value in that tenantid column when data is saved by a particular tenant

**Comment by 274188A** [comment]
ok - I see.  So if a tenant saves something, then that data is exposed to every other tenant until somebody manually goes into the database and set the tenant ID.  Am I understanding that right?

**Comment by 274188A** [comment]
I'm not expecting RBS to add a column.

I am expecting the code generated to save the correct tenantID value into that TenantID column.

**Comment by akorchev** [comment]
I think I have explained the current situation in my previous replies. We don't plan on changing the current implementation.

**Comment by 274188A** [comment]
I see - so you cant save a tenantID in a tenantID column - I wish I knew that...

**Comment by 274188A** [comment]
OK, I'll accept that as a solution.  However I have just done exactly that and the data is not filtered correctly per tenant (Global Filter).  Each tenant can see each other's data despite the tenant id being set for the own record.

It's late here and I will endeavour to raise a new issue as this is a different topic and give you a sample tomorrow.
