### ISSUE TITLE
on startup of project build claims failed

### ISSUE THREAD

**Issue by 7045kHz** [radzenhq/radzen-blazor-studio#101]
Situation: 
When loading a project created by Radzen Blazor Studio, GUI claims build failed. Output error is "C:\src\wwwroot\". However, project will run in Release and Debug mode.  This failulre prevents the loading of Design window.

Note that both Radzen Blazor Studio and Visual Studio 2022 can build and run the project.

**Comment by 7045kHz** [comment]
Radzen Blazor Studio is version 1.8.1,  running on Windows 11, and license is paid for.

**Comment by akorchev** [comment]
You can check the [troubleshooting](https://www.radzen.com/blazor-studio/documentation/troubleshooting/) guide. If you still can't make it work please send us your project to info@radzen.com so we can check it.

**Comment by akorchev** [comment]
I am closing the issue due to inactivity.
