### ISSUE TITLE
Unable to Update DocumentFormat.OpenXml NuGet Library from 2.19.0 to 2.20.0

### ISSUE THREAD

**Issue by BillEisenman** [radzenhq/radzen-blazor-studio#102]
I am unable to Update DocumentFormat.OpenXml NuGet Library to 2.20.0 from 2.19.0. The Error generated on Compile is 
'OpenXmlUnknownElement.CreateOpenXmlUnknownElement(string)' is obsolete; Use the extension method 'CreateUnknownElement' off of a part container. This Library Method is used on Line 342 of the ExportController.cs as follows:
 OpenXmlUnknownElement openXmlUnknownElement4 = OpenXmlUnknownElement.CreateOpenXmlUnknownElement("<x15:timelineStyles defaultTimelineStyle=\"TimeSlicerStyleLight1\" xmlns:x15=\"http://schemas.microsoft.com/office/spreadsheetml/2010/11/main\" />");

Currently can only update NuGet Libaray to v2.19.0.

**Comment by BillEisenman** [comment]
Any Update? I actually gave the specific line in the ExportController.cs to update.

**Comment by enchev** [comment]
Hey @BillEisenman,

Unfortunately Microsoft decided to introduce breaking change in a minor version :(. Here is how to update your code to update to 2.20.0:
```
...
OpenXmlUnknownElement openXmlUnknownElement4 = workbookStylesPart1.CreateUnknownElement("<x15:timelineStyles defaultTimelineStyle=\"TimeSlicerStyleLight1\" xmlns:x15=\"http://schemas.microsoft.com/office/spreadsheetml/2010/11/main\" />");
...
```

We will update our templates.
