### ISSUE TITLE
RBS does not keep history of applications opened

### ISSUE THREAD

**Issue by 274188A** [radzenhq/radzen-blazor-studio#108]
this is always the same even if applications were opened using the RBS:

![image](https://user-images.githubusercontent.com/40014477/237046731-6296ba28-58ca-4188-8dbc-7fb00dc2723f.png)

**Comment by akorchev** [comment]
A similar message is displayed by Visual Studio code. Why does it bother you? 
<img width="383" alt="image" src="https://user-images.githubusercontent.com/454726/237047285-e228a79e-3d5a-4c0b-9a89-fdadcd24c0ea.png">

**Comment by BustosAndrew** [comment]
@akorchev I think what @274188A means is that it would be preferable if we could open recent applications, similar to opening recent folders/files. I think @274188A got confused and thought it was a bug that it didn't show recently opened apps. Nonetheless, could we get a feature soon that shows recently opened apps?

**Comment by 274188A** [comment]
I misunderstood how this worked
