### ISSUE TITLE
Explorer tab filter issue

### ISSUE THREAD

**Issue by koksalbasar** [radzenhq/radzen-blazor-studio#113]
Hi team,

If you type "user" find file box in the explorer tab the filter is not working properly.

![image](https://github.com/radzenhq/radzen-blazor-studio/assets/56689928/da727c1b-73f5-49e3-9e55-7d4c1347df2c)

**Comment by akorchev** [comment]
Took me a while to find why it doesn't work until it hit me - filtering works for the full path at the moment which is unexpected. Your application is probably in `c:\Users\....` which is why all files match `user`. We will change the filtering to only work on file names.
