### ISSUE TITLE
Title page does not show

### ISSUE THREAD

**Issue by dreeddri** [radzenhq/radzen-blazor-studio#114]
I was NOT having this issue until loading the latest version which was supposed to FIX this issue!
Thanks

**Comment by akorchev** [comment]
Please provide more info:

- Version
- OS

Also check the log file for any errors.

**Comment by akorchev** [comment]
Nevermind I think I got it. A new release is in the works.

**Comment by figuerres** [comment]
i hope this will be a fix to the fix..... i got two updates today, the second one broke the app....
looking to see if i need to uninstall to get things back....
enter licence key and check for updates etc.... seem to be broken also...

**Comment by akorchev** [comment]
We have just released 1.12.3. You need to download it again as autoupdate won't work in 1.12.2.

**Comment by figuerres** [comment]
thanks for the info! 
 yeah that 1.12.2 is like 100% fubar! lol

**Comment by dreeddri** [comment]
Thanks for the very quick response!

Sent from Mail for Windows

**Comment by figuerres** [comment]
> We have just released 1.12.3. You need to [download](https://www.radzen.com/blazor-studio/download) it again as autoupdate won't work in 1.12.2.

looks like the .3 update does restore things to working now !!! :-)
