### ISSUE TITLE
Blazor Server App: Perpetually in the "Building" state.

### ISSUE THREAD

**Issue by A9G-Data-Droid** [radzenhq/radzen-blazor-studio#116]
RADZEN VERSION: 1.13.2

If I click the `Run` in the upper right corner, the project is built and runs fine. The editor is unusable as it's perpetually in the "Building" state. It is unacceptable to let the user wait forever expecting something to happen. Don't show a progress bar when you should show an error. This is an awful user experience.

There is no error in the log file, so that's likely why the UI doesn't know it's in an error state either.

LOOKS LIKE THIS:
![image](https://github.com/radzenhq/radzen-blazor-studio/assets/26984068/8fbb9c7a-d880-48f8-84e6-d5a3c2df3cb8)

If I run the analyze command from the troubleshooting page I get a logging related error:

> Microsoft.Build.Exceptions.InternalLoggerException: The build stopped unexpectedly because of an unexpected logger failure.
> ---> Microsoft.Build.Exceptions.InternalLoggerException: The build stopped unexpectedly because of an unexpected logger failure.
> ---> System.ArgumentNullException: Value cannot be null. (Parameter 'fileName')
>    at Microsoft.CodeAnalysis.MSBuild.Logging.MSBuildDiagnosticLogItem..ctor(WorkspaceDiagnosticKind kind, String projectFilePath, String message, String fileName, Int32 lineNumber, Int32 columnNumber)
>    at Microsoft.CodeAnalysis.MSBuild.Logging.MSBuildDiagnosticLogger.OnWarningRaised(Object sender, BuildWarningEventArgs e)
>    at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseWarningEvent(Object sender, BuildWarningEventArgs buildEvent)
>    --- End of inner exception stack trace ---
>    at Microsoft.Build.Exceptions.InternalLoggerException.Throw(Exception innerException, BuildEventArgs e, String messageResourceName, Boolean initializationException, String[] messageArgs)
>    at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseWarningEvent(Object sender, BuildWarningEventArgs buildEvent)
>    at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)
>    --- End of inner exception stack trace ---
>    at Microsoft.Build.Exceptions.InternalLoggerException.Throw(Exception innerException, BuildEventArgs e, String messageResourceName, Boolean initializationException, String[] messageArgs)
>    at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)
>    at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseWarningEvent(Object sender, BuildWarningEventArgs buildEvent)
>    at Microsoft.Build.BackEnd.Logging.LoggingService.RouteBuildEvent(BuildEventArgs eventArg)
>    at Microsoft.Build.BackEnd.Logging.LoggingService.RouteBuildEvent(Object loggingEvent)
>    at Microsoft.Build.BackEnd.Logging.LoggingService.LoggingEventProcessor(Object loggingEvent)
> --- End of stack trace from previous location ---
>    at Microsoft.Build.Execution.BuildManager.EndBuild()
>    at Microsoft.CodeAnalysis.MSBuild.Build.ProjectBuildManager.EndBatchBuild()
>    at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.LoadAsync(CancellationToken cancellationToken)
>    at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.LoadSolutionInfoAsync(String solutionFilePath, IProgress`1 progress, ILogger msbuildLogger, CancellationToken cancellationToken)
>    at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.OpenSolutionAsync(String solutionFilePath, ILogger msbuildLogger, IProgress`1 progress, CancellationToken cancellationToken)
>    at Radzen.Server.SolutionContext.OpenAsync(MSBuildWorkspace workspace, String fileName)
>    at Radzen.Server.SolutionContext.BuildAsync(String fileName, Boolean throwOnBuildError)
>    at Radzen.Server.SolutionFacade.LoadProject(String filePath, Boolean overrideLifeCycle, Boolean throwOnBuildError)
>    at Radzen.Server.ProjectAnalyzer.AnalyzeAsync(String path, IServiceProvider serviceProvider, Boolean parallel, Boolean all)
> Finished with errors.

**Comment by akorchev** [comment]
As discussed over email we need access to a project in order to reproduce this problem. Closing as there isn't anything we can do at the moment.

**Comment by A9G-Data-Droid** [comment]
That's not true. If you had a logging system that worked, troubleshooting could be done with anonymous information that doesn't expose full source code to a 3rd party. The stack trace I gave you is, ironically enough, a failure of that logging system we need for troubleshooting. 

Maybe if you post your full source code here on GitHub then the community could help you debug this problem.

**Comment by akorchev** [comment]
The stacktrace ends, ironically enough, in the Microsoft Roslyn framework which fails to open your project ... Not sure how open sourcing our product would allow anybody to debug the Roslyn code.

**Comment by A9G-Data-Droid** [comment]
The same way that opening the source of my project helps you debug your code. I was hoping that irony was not lost on you.

Roslyn has no problem opening my project outside of you software. I get warnings from Roslyn and I close them out.
