### ISSUE TITLE
Problems with dotnet 8 - query top max

### ISSUE THREAD

**Issue by dreeddri** [radzenhq/radzen-blazor-studio#124]
The queries for the generated CRUD pages do not work.  They return that a max top value of 0 was exceeded (default is 10)

I had to add the following:
builder.Services.AddControllers().AddOData(options => options.Select().Filter().Count().OrderBy().Expand().SetMaxTop(1000));

To the AddControllers line.

Also, AUTO rendering CRFUD forms not working, and hierarchical grids not being generated.

Thanks

**Comment by akorchev** [comment]
Hi @dreeddri,

We reproduced the problem. It happens when a database is inferred every second time. Some vital code (OData controller registration) is removed from Program.cs every second time. We will release a fix later today.

**Comment by akorchev** [comment]
The latest release should address this issue.
