### ISSUE TITLE
No access to themes

### ISSUE THREAD

**Issue by Ironoak** [radzenhq/radzen-blazor-studio#127]
I have an ASP DotNet Core Blazor server project that has been build with the free Nuget-Package of Radzen.Blazor.
After purchasing a license I can open the project in RBS but I am not able to make use of the themes/appearances feature.

RBS says "The appearance settings require the Radzen.Blazor Components. Add Radzen.Blazor to your application ...".

I cannot see what's missing here and recreating the project in RBS is no option for me.
How should I proceed to leverage the themes feature in my paid license?

**Comment by akorchev** [comment]
Hi @Ironoak,

Please send us your application to info@radzen.com and we will check why this happens. You can upload it to some cloud storage provider and share a download link with us. Or you can delete the bin and obj directories and send it as attachment.

**Comment by akorchev** [comment]
In that case we can't do much else.
