### ISSUE TITLE
RadzenDataGrid - Save / Load Settings - AllowColumnPicking - Inline Editing Column Not saving.

### ISSUE THREAD

**Issue by paulgoldbergus** [radzenhq/radzen-blazor-studio#129]
Added the Allow column picking and the state saves for all the other columns but not the column which contains the inline editing. The column selector will work correctly but the save state and load state fail to reload this column.

I noticed this is the only column with an EditTempate tag.

Paul

**Comment by akorchev** [comment]
Hi, this issue seems related to the Radzen.Blazor component library. Please use our forum for such questions or if you believe you have found a bug - log an issue in the radzen-blazor repository.
