### ISSUE TITLE
I create an empty project and Designer not working

### ISSUE THREAD

**Issue by HolyOne** [radzenhq/radzen-blazor-studio#132]
Blazor Studio version: 1.22.1
I created a new webassembly project (.net8 blazor)

When I click index.razor file I see this in the output

D:\Temp\AutoDirectory500\test5\Server\Program.cs(2,20): error CS0234: The type or namespace name 'Components' does not exist in the namespace 'Test5.Server' (are you missing an assembly reference?)
D:\Temp\AutoDirectory500\test5\Server\Program.cs(27,24): error CS0246: The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?)
D:\Temp\AutoDirectory500\test5\Server\Program.cs(27,113): error CS0234: The type or namespace name '_Imports' does not exist in the namespace 'Test5.Client' (are you missing an assembly reference?)

And designer is not working

**Comment by akorchev** [comment]
A couple of questions.
- Is the D:\ drive a normal drive or a mapped or network drive? If it is there could be problems.
- Do you have a third party nuget source setup as the default one? If yes you can check here: https://www.radzen.com/blazor-studio/documentation/troubleshooting/#package-restore-errors

Also there are probably more errors that appear before those two. Can you paste them as well?

**Comment by HolyOne** [comment]
D: drive is normal disk.
I dont have a third party nuget. I just created a new .net 8 project using blazor studio.

**Comment by akorchev** [comment]
This issue seems to be caused by having a preview version of the .NET framework installed. More recent versions of Radzen Blazor Studio would notify in this case. Unfortunately we can't support preview versions of the .NET SDK.
