### ISSUE TITLE
Message "Failed to start development server"

### ISSUE THREAD

**Issue by GetHiTC** [radzenhq/radzen-blazor-studio#134]
Can't run Radzen Blazor studio, keep getting "Failed to bind to address http://localhost:4000."
Also, can't copy the text from the error message box so here's a screenshot. Really should change this app to be able to copy error text.

I would try a different port but I can't find any way to change this setting. I uninstalled and resinstalled the RB studio, also rebooted, also searched for processes using that port but there are none, also ran RB studio as admin, no joy.

![image](https://github.com/radzenhq/radzen-blazor-studio/assets/86384775/5269fa25-6dfb-498e-90e9-b4b37ed34d1c)

**Comment by GetHiTC** [comment]
The problem was contention with SQL Server 2022. I uninstalled it and rebooted Radzen Studio then worked fine. Seems to be that SQL Serever changes the network configuration somehow because netstat showed no active servers on port 4000.

**Comment by dvdobrovolskiy** [comment]
Same story. also cannot copy error

![Image](https://github.com/user-attachments/assets/bdf45a89-d377-42b0-859d-2b379a721448)

Nothing sits on 4000 for sure. Nothing at all. Problem is, I need MS SQL 2022
