### ISSUE TITLE
When Filter in Demo for Grid is Cleared Does not Call the specified Filter Event.

### ISSUE THREAD

**Issue by paulgoldbergus** [radzenhq/radzen-blazor-studio#135]
In the Demo the Grid call Reset when the Filter bar is used and this will clear any Add/Edit state and enable the Add Button. If the Filter is  set before the Add Button is used putting it in an add state and then the clear filter of the column is used it will clear the filter but not call the Filter Reset event hence leaving the Add Button Disabled.

**Comment by paulgoldbergus** [comment]
The above is not working in the Demo but this was the same issue I experienced and took a long time to find. I am unable to move to the next release until this bug is resolved. Do you have a timeline for this?

**Comment by akorchev** [comment]
This doesn't sound related to Radzen Blazor Studio. You can use our forum for questions or send us an email to info@radzen.com if you have an active subscription.
