### ISSUE TITLE
External authentication Facebook, Twitter and Webassembly Auto Mode

### ISSUE THREAD

**Issue by HolyOne** [radzenhq/radzen-blazor-studio#140]
Hello, I see that Radzen blazor studio has its own SecurityService class for authentication.
Is it possible to use external authentication with Radzen?

I tried regular Blazor Account pages but it causes infinite loop in Login page.
I tried to add twitter external login lines to program.cs but I dont see twitter login buttons.
is there an example project for it anywhere?

**Comment by akorchev** [comment]
No, I am afraid this isn't supported out of the box and we don't have any demos available.

**Comment by HolyOne** [comment]
Thats a huge feature to lose for switching to a UI component pack :(
I hope you can integrate standard microsoft authentication to radzen project templates in the future

**Comment by akorchev** [comment]
This doesn't have to do anything with a UI component stack. You can use the security templates provided from Microsoft.
