### ISSUE TITLE
SMTP Client has a bug?

### ISSUE THREAD

**Issue by VR-Architect** [radzenhq/radzen-blazor-studio#146]
I started a new Radzen Blazor Studio app and added ASP.NET Core Identity security. When registering a new user via the application's sign-up button, a error occurs 

   "Syntax error, command unrecognized. The server response was: "

on line:     await client.SendMailAsync(mailMessage);

The error message was cut off and mostly worthless. I tried with multiple SMTP services and same results. I swapped out the method with a library called MailKit.Net.Smtp and the email went through just fine. So this leads me to think there is a bug in System.Net.Mail of .NET v8.x

Just letting Radzen know this in case you wish to either swap out that library or let others know.

**Comment by akorchev** [comment]
We have been using System.Net.Mail every single day for years and it has worked flawlessly. Probably your mail server's configuration somehow prevents it from working. Feel free to replace it with whatever works for you.

**Comment by VR-Architect** [comment]
So because your team has been using it for years there is no issue and you just close the ticket? Not very good customer service for your Pro users. Which version of the library is your team using? Have they tried to repeat the same steps your Pro users are doing to create a new project using .NET version 8? Are you implying I used your tool wrong by just clicking the buttons and hitting run?

**Comment by akorchev** [comment]
Hi @VR-Architect,

We do not provide customer support here. Please contact us at info@radzen.com to discuss this matter further.
