### ISSUE TITLE
Create new page does not work

### ISSUE THREAD

**Issue by mdchafin** [radzenhq/radzen-blazor-studio#15]
See the video at https://www.screencast.com/t/tujw5Xarv38

**Comment by akorchev** [comment]
Does it work if you don't add `.razor` in the name (we add that automatically)?

**Comment by mdchafin** [comment]
It does not.

**Comment by akorchev** [comment]
I recorded a gif showing what is supposed to happen when a new page is created:
![create-page](https://user-images.githubusercontent.com/454726/160833870-b2884ff7-0866-4bf1-96a1-3c2f2eed5385.gif)

**Comment by mdchafin** [comment]
[BlazorForm.zip](https://github.com/radzenhq/radzen-blazor-studio/files/8381651/BlazorForm.zip

The code from above

**Comment by gparissis** [comment]
> [BlazorForm.zip](https://github.com/radzenhq/radzen-blazor-studio/files/8381651/BlazorForm.zip
> 
> The code from above

Same error here.

**Comment by akorchev** [comment]
This application is using .NET 3.1 which RBS does not support. It supports .NET 5 and .NET 6 apps only.

```
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
```

We will add a check to prevent RBS from opening such applications. Also make sure to mention it in the documentation.

**Comment by gparissis** [comment]
Hi,

Please see the attached video. I am not using 3.1 and the Blazor project is the standard project template created with VS 2022.
https://www.screencast.com/t/4pOSFkBag94

**Comment by akorchev** [comment]
This issue is about a .NET 3.1 application and that's why it was closed.

**Comment by gparissis** [comment]
> This issue is about a .NET 3.1 application and that's why it was closed.



> This issue is about a .NET 3.1 application and that's why it was closed.

My apologies then. I just wanted to inform that an error is raised even with version 6.
