### ISSUE TITLE
Close file tabs on mouse middle-click

### ISSUE THREAD

**Issue by yordanov** [radzenhq/radzen-blazor-studio#17]
Via https://forum.radzen.com/t/radzen-blazor-studio-feature-request/10513

"By pressing Scrollwheel on the mouse while hover over an open page closes the page just like in a web browser. So you can press either the "X" button or click on the mousewheel to close a page. It would make things just a little better."

**Comment by AnNormalie** [comment]
@akorchev 
just encountered, that when you have more tabs open than it can display than it will not close the tab on middle mouse press, instead it will show up the scroll symbol again.
