### ISSUE TITLE
Red text when error hits

### ISSUE THREAD

**Issue by hampusWisest** [radzenhq/radzen-blazor-studio#21]
When an compile error occur the text turns red with grey background and does not go back to normal white with black background until I restart  RBS.

![image](https://user-images.githubusercontent.com/63351366/161727383-9a9e5587-148d-4a65-bf3d-ddd89311681a.png)

**Comment by akorchev** [comment]
Radzen Blazor Studio displays the output of `dotnet watch run`. What happens if you manually execute `dotnet watch run` in your application and perform the same steps?

**Comment by hampusWisest** [comment]
Powershell Dotnet watch run output
![image](https://user-images.githubusercontent.com/63351366/161935931-4196f974-c55e-485d-bfa4-163c2adbde3a.png)

Same project in RBS output
![image](https://user-images.githubusercontent.com/63351366/161936848-254ebf3a-7fa5-449f-97c1-b0ad0a7c08d8.png)

**Comment by akorchev** [comment]
Thanks! Unfortunately this could be a bug with the component that we use for the output. We will investigate further.

**Comment by akorchev** [comment]
We have released 1.0.0.preview.8 which should address this issue.

**Comment by hampusWisest** [comment]
![image](https://user-images.githubusercontent.com/63351366/163381229-4000441f-033c-4de3-b95b-2945f27f15b2.png)

Now its always white? The image i provided now has 3 errors rows and 1 watch, all of themare white. Is this intended?

**Comment by akorchev** [comment]
No, it should look like this:

<img width="905" alt="image" src="https://user-images.githubusercontent.com/454726/163382102-6436b618-350a-41e9-aa9e-ccc3fe88c5c0.png">

Here there is an error and later it is fixed - the color changes from red to white as expected.

**Comment by hampusWisest** [comment]
I can now confirmed that the issue is fixed in 1.0.0.preview.8
![image](https://user-images.githubusercontent.com/63351366/163383623-2ca7ac45-5656-4d4d-8a71-a5236fff3061.png)
