### ISSUE TITLE
Project still running when closing RBS

### ISSUE THREAD

**Issue by hampusWisest** [radzenhq/radzen-blazor-studio#23]
If i start the project and then close RBS via the "x" button or via "Window -> Close", a process for the IIS site(?) is still running and must be ended via Task Manager or powershell. If you open the project again, you cannot start the project until the process is ended.

![image](https://user-images.githubusercontent.com/63351366/161938763-6b3be208-49a6-4bd9-a807-ddab4b9b5f04.png)

**Comment by akorchev** [comment]
We tried to fix that with the latest release 1.0.0.preview.7.

**Comment by hampusWisest** [comment]
Confirmed issue resolved in 1.0.0.preview.7
