### ISSUE TITLE
New page creation exception. Incorrectly the thread was closed

### ISSUE THREAD

**Issue by gparissis** [radzenhq/radzen-blazor-studio#25]
Please watch the video that I posted in this incorrectly closed thread. https://github.com/radzenhq/radzen-blazor-studio/issues/15

By the way, just so that I know, is anyone monitoring the closed threads for updates?

Thank you.

**Comment by akorchev** [comment]
Which version are you using? The issue from the video should have been fixed some time ago.

**Comment by gparissis** [comment]
> Which version are you using? The issue from the video should have been fixed some time ago.

At the time I created the video I was using preview 2.

**Comment by akorchev** [comment]
We are at preview.6 at the moment. You can get it from the download page: http://www.radzen.com/blazor-studio/download/#macOS

**Comment by gparissis** [comment]
Great news. I will update and retry.

Thanks again and sorry for the misunderstanding.

**Comment by akorchev** [comment]
I am closing this issue as it should be fixed. Feel free to open a new one or write here if the problem persists.
