### ISSUE TITLE
Default Blazor Web Assembly Fails to run

### ISSUE THREAD

**Issue by vinoopillai** [radzenhq/radzen-blazor-studio#26]
Hello,
Wasm application created with default template using below settings
![image](https://user-images.githubusercontent.com/86370143/163379154-e1f99355-c196-441a-bb8d-84ecb44eb400.png)

The project is opened but fails to execute in RBS with below error message
![image](https://user-images.githubusercontent.com/86370143/163378859-d0d29eb7-8615-4f73-a813-df26b423ed35.png)

But the same runs in VS without any issue.

**Comment by akorchev** [comment]
Please attach the application so we can test.

**Comment by vinoopillai** [comment]
The issue is for default WASM template project from visual studio 2022. I have attached the application
[test.zip](https://github.com/radzenhq/radzen-blazor-studio/files/8489006/test.zip)

**Comment by akorchev** [comment]
Thanks! We reproduced the problem and will fix it with the nest release.

**Comment by akorchev** [comment]
We have released 1.0.0.preview.9 which should address this issue.

**Comment by vinoopillai** [comment]
The issue is now resolved. Thanks
