### ISSUE TITLE
New page creation failed

### ISSUE THREAD

**Issue by basztech** [radzenhq/radzen-blazor-studio#27]
Hi,
I tried to create a new page with code behind in a .NET6 WASM app using CTP8 and got the following error:

`{Name}.razor.cshtml(4,41): error CS0234: The type or namespace name 'Razor' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
{Name}.razor.cshtml(12,32): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
{Name}.razor.cshtml(13,32): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
{Name}.razor.cshtml(14,32): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
{Name}.razor.cshtml(22,35): error CS0234: The type or namespace name 'Razor' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
{Name}.razor.cshtml(23,63): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
{Name}.razor.cshtml(80,45): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
{Name}.razor.cshtml(82,45): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
{Name}.razor.cshtml(84,45): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
{Name}.razor.cshtml(86,45): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
{Name}.razor.cshtml(88,45): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
{Name}.razor.cshtml(26,67): error CS0115: '__Name__razor.ExecuteAsync()': no suitable method found to override
{Name}.razor.cshtml(79,39): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
{Name}.razor.cshtml(81,39): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
{Name}.razor.cshtml(83,39): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
{Name}.razor.cshtml(85,39): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
{Name}.razor.cshtml(87,39): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
{Name}.razor.cshtml(28,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
C:\Dev\ellzeycrm\client\{Name}.razor.cshtml(3,4): error CS0103: The name 'Write' does not exist in the current context
C:\Dev\ellzeycrm\client\{Name}.razor.cshtml(3,10): error CS0103: The name 'Model' does not exist in the current context
{Name}.razor.cshtml(36,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
C:\Dev\ellzeycrm\client\{Name}.razor.cshtml(4,7): error CS0103: The name 'Model' does not exist in the current context
{Name}.razor.cshtml(45,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
{Name}.razor.cshtml(46,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
C:\Dev\ellzeycrm\client\{Name}.razor.cshtml(9,10): error CS0103: The name 'Model' does not exist in the current context
{Name}.razor.cshtml(55,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
{Name}.razor.cshtml(56,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
{Name}.razor.cshtml(57,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
{Name}.razor.cshtml(58,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
{Name}.razor.cshtml(67,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
{Name}.razor.cshtml(68,13): error CS0103: The name 'WriteLiteral' does not exist in the current context

   at Radzen.Server.ProjectContext.Compile(Compilation compilation, AssemblyLoadContext context) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectContext.cs:line 122
   at Radzen.Server.ProjectServer.CompileTemplate(String fileName, String source, RazorProjectEngine projectEngine, AssemblyLoadContext context) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 819
   at Radzen.Server.ProjectServer.RenderTemplate[T](String path, String content, T model) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 189
   at Radzen.Server.CodeGenerationTemplateGenerator`1.GenerateAsync(ProjectServer server, String outputPath, String name, CancellationToken token) in /Users/korchev/github/radzen-next/Radzen.Server/CodeGeneratorService.cs:line 228
   at Radzen.Server.CodeGenerationService.<>c__DisplayClass5_1.<<Generate>b__1>d.MoveNext() in /Users/korchev/github/radzen-next/Radzen.Server/CodeGeneratorService.cs:line 116`

**Comment by akorchev** [comment]
Hi @basztech, we released 1.0.0.preview.9 which could address this issue. Please try it and let us know. If you feel experience the same exception please attach your app here so we can investigate further.

**Comment by basztech** [comment]
Thank you!, The new page works without error in the new CTP @akorchev.

**Comment by basztech** [comment]
Great job!
