### ISSUE TITLE
CSS does not load in design time

### ISSUE THREAD

**Issue by basztech** [radzenhq/radzen-blazor-studio#28]
Hi,

I am using the Fluent css with the includes built by Radzen Studio but the css is not coming through in the design time window. I'm not sure if it is a bug or a known limitation. 

Your article at https://www.radzen.com/blazor-studio/documentation/troubleshooting/#css-does-not-load-in-design-time states that it should be picked up unless the css is included by other means. It appears that including css files from within styles.css no longer works and we have to explicitly add each file to index.html.

**Comment by basztech** [comment]
I have to add that once setup, the new design time experience is very good. Being able to dynamically edit the css through style sheets in the same design tool is a fantastic feature!

**Comment by akorchev** [comment]
>  It appears that including css files from within styles.css no longer works and we have to explicitly add each file to index.html.

This is supposed to work. Could you attach a sample app where CSS files fail to load?

**Comment by basztech** [comment]
I have created a new project in Radzen Studio using the Fluent theme and added an additional css file, test.css. It looks like Radzen Blazor Studio is picking up my test.css but not the Fluent css.
![image](https://user-images.githubusercontent.com/84408121/163813071-fb1557bb-5cad-44f9-95b8-722d1e5fae5a.png)

**Comment by akorchev** [comment]
Here is what I see when I open the application you have sent us: 
<img width="1515" alt="image" src="https://user-images.githubusercontent.com/454726/163935850-2bb29e88-86ee-45d4-9d8a-54149c21ad01.png">

Screenshot was taken from Windows 11 running latest Radzen Blazor Studio.

Can you provide some more info about your system? I wonder what could be different in your setup.

**Comment by basztech** [comment]
Here is a snippet from systeminfo:

`OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19044 N/A Build 19044
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 61 Stepping 4 GenuineIntel ~2000 Mhz
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     8,119 MB
Available Physical Memory: 2,863 MB
Virtual Memory: Max Size:  14,775 MB
Virtual Memory: Available: 8,865 MB
Virtual Memory: In Use:    5,910 MB`

I also have Visual Studio 2022 community edition.

**Comment by akorchev** [comment]
Hi @basztech I have sent you a debug build of Radzen Blazor Studio over email with some additional troubleshooting instructions. Hopefully this would allow us to understand why CSS files fail to load for you.

**Comment by akorchev** [comment]
The issue that was causing this problem should be resolved in 1.0.0.preview.10.
