### ISSUE TITLE
Radzen Blazor Studio incorrectly reporting errors "CS0107: More than one protection modifier"

### ISSUE THREAD

**Issue by ApolonTorq** [radzenhq/radzen-blazor-studio#29]
Using Preview 10, the following errors appear in the output window. Most of the lines referred to are actually comment lines and the CS0107 errors do not occur when building in VS/Rider/dotnet-build as there aren't any multiple protection modifier statements.

Its almost as if the actual source is being modified in memory before being compiled from within RBS.

``` text
C:\Code.Insight\Apps.Iris\DotNet\Torq\Foundation\Tests\TorqTest.cs(200,23): error CS0107: More than one protection modifier
C:\Code.Insight\Apps.Iris\DotNet\Torq\Foundation\TorqObject.cs(2066,31): error CS0107: More than one protection modifier
C:\Code.Insight\Apps.Iris\DotNet\Torq\Foundation\Externals\Externalizable.cs(192,25): error CS0107: More than one protection modifier
C:\Code.Insight\Apps.Iris\DotNet\Torq\Foundation\Externals\Externalizable.cs(214,22): error CS0107: More than one protection modifier
C:\Code.Insight\Apps.Iris\DotNet\Torq\Foundation\Externals\Externalizable.cs(236,25): error CS0107: More than one protection modifier
C:\Code.Insight\Apps.Iris\DotNet\Torq\Foundation\Externals\Externalizable.cs(258,24): error CS0107: More than one protection modifier
C:\Code.Insight\Apps.Iris\DotNet\Torq\Foundation\Externals\Externalizable.cs(280,23): error CS0107: More than one protection modifier
C:\Code.Insight\Apps.Iris\DotNet\Torq\Foundation\Externals\Externalizable.cs(302,26): error CS0107: More than one protection modifier
C:\Code.Insight\Apps.Iris\DotNet\Torq\Foundation\Externals\Externalizable.cs(324,27): error CS0107: More than one protection modifier
C:\Code.Insight\Apps.Iris\DotNet\Torq\Foundation\Externals\Externalizable.cs(346,28): error CS0107: More than one protection modifier
C:\Code.Insight\Apps.Iris\DotNet\Torq\Foundation\Externals\Externalizable.cs(368,24): error CS0107: More than one protection modifier
C:\Code.Insight\Apps.Iris\DotNet\Torq\Foundation\Externals\Externalizable.cs(390,23): error CS0107: More than one protection modifier
C:\Code.Insight\Apps.Iris\DotNet\Torq\Foundation\Externals\Externalizable.cs(414,27): error CS0107: More than one protection modifier
C:\Code.Insight\Apps.Iris\DotNet\Torq\Foundation\Externals\Externalizable.cs(436,20): error CS0107: More than one protection modifier
C:\Code.Insight\Apps.Iris\DotNet\Torq\Foundation\Externals\Externalizable.cs(471,31): error CS0107: More than one protection modifier
C:\Code.Insight\Apps.Iris\DotNet\Torq\Foundation\Externals\Externalizable.cs(502,30): error CS0107: More than one protection modifier
C:\Code.Insight\Apps.Iris\DotNet\Torq\Foundation\Externals\Externalizable.cs(524,22): error CS0107: More than one protection modifier
C:\Code.Insight\Apps.Iris\DotNet\Torq\Foundation\TorqPropertyBag.cs(231,25): error CS0107: More than one protection modifier
C:\Code.Insight\Apps.Iris\DotNet\Torq\Foundation\TorqPropertyBag.cs(240,23): error CS0107: More than one protection modifier
C:\Code.Insight\Apps.Iris\DotNet\Torq\Foundation\TorqList.cs(611,23): error CS0107: More than one protection modifier
C:\Code.Insight\Apps.Iris\DotNet\Torq\Foundation\TorqList.cs(625,23): error CS0107: More than one protection modifier
```

**Comment by akorchev** [comment]
> Its almost as if the actual source is being modified in memory before being compiled from within RBS.

RBS does modify some of the source however it shouldn't process commented code. Can you paste some of the code which causes the problem? If possible you can send us the source app to info@radzen.com

**Comment by ApolonTorq** [comment]
I can't practically send you the source app but will try and reproduce the error in a smaller project that I can send you.

**Comment by akorchev** [comment]
Thanks! That would help a lot.

**Comment by akorchev** [comment]
Just released 1.0.0.preview.11 which should address this issue.

**Comment by ApolonTorq** [comment]
I can confirm that Preview 11 fixed the errors from the cut down demo project that was sent to you. Running Preview 11 against the entire app uncovered additional issues reporting inconsistent accessibility for members and types that are all internal i.e. actually consistent accessibility. I’ve included a bit more into the cut down demo project and resent it. That project reproduces the inconsistent accessibility problem.

**Comment by akorchev** [comment]
Hi @ApolonTorq,

We haven't received a new email from you. Our email server does not allow files bigger than 20MB so if the project is too big it may not have passed. You can delete any bin and obj directories to reduce the file size.

**Comment by ApolonTorq** [comment]
The email bounced because of the inclusion of a dll in the zip file which violated the email server's policy. I'll re-arrange and resend with instructions.

**Comment by ApolonTorq** [comment]
Thanks, that fixed the initial build errors in the blazor app based on an existing set of non-visual application libraries I am working with. There are further issues but they related to the operation of the design surface so will be the subject of another issue.
