### ISSUE TITLE
Issue with file scoped namespaces

### ISSUE THREAD

**Issue by AnNormalie** [radzenhq/radzen-blazor-studio#3]
In my project, created with Radzen I have some custom services or partial model classes that have a file scoped namespace.
It seems that Radzen Blazor Studio could not handle this.

eg. a partial class to a generated `Equipment` model class:
```csharp
using System.ComponentModel.DataAnnotations.Schema;

namespace TestManyToMany.Models.dbietest;


public partial class Equipment
{
    [NotMapped]
    public string CustomProp { get; set; } = string.Empty;
}

```

**Comment by akorchev** [comment]
Could you elaborate what the issue is?

**Comment by akorchev** [comment]
We have updated the C# grammar so the syntax highlighting should work correctly in 1.0.0.preview.8 (not released yet).
