### ISSUE TITLE
Position in opened file reset to top after changing tab

### ISSUE THREAD

**Issue by AnNormalie** [radzenhq/radzen-blazor-studio#33]
Steps to reproduce:
- open 2 or more files with code (doesn't matter if it is a *.razor or *.razor.cs file) in `SOURCE` view.
- scroll down in one of these files
- switch the tab to another opened file
- go back to the previous file
- The page is back to top and not at the position where we previously scrolled to.

**Comment by AnNormalie** [comment]
Hi @akorchev 
just checked it with 1.0.0.preview.13, but unfortunately it doesn't seem to work. When switching back to a tab, then its reset to top.

**Comment by akorchev** [comment]
Confirmed. It doesn't work in some (most?) cases as it is now. Will fix it with the next release.

**Comment by AnNormalie** [comment]
It is working with 1.0.0.preview.14
