### ISSUE TITLE
Tabs could not be closed on middle mouse press when tab bar is full

### ISSUE THREAD

**Issue by AnNormalie** [radzenhq/radzen-blazor-studio#34]
When you have more tabs open than it can display than it will not close the tab on middle mouse press, instead it will show up the scroll symbol again.

**Comment by AnNormalie** [comment]
Hi @akorchev it seems to work, 
but just saw that now right clicking a tab also closes it, is this as intended?

**Comment by akorchev** [comment]
Not intended! Will fix it in the next release.
