### ISSUE TITLE
[Feature] Unable to apply hot reload because of rude edit

### ISSUE THREAD

**Issue by AnNormalie** [radzenhq/radzen-blazor-studio#36]
It would be nice that in case of an rude edit, the `Output Window` would accept the option to choose how to go on.

![image](https://user-images.githubusercontent.com/86982835/168376060-e0c63dd5-368a-464c-9da2-fee9a6d15cf4.png)

**Comment by AnNormalie** [comment]
Yes its a nice to have, please see it as a feature request.

Thanks

**Comment by akorchev** [comment]
We did further research and it seems very hard to implement at the moment (if not close to impossible). Will leave the issue open just in case.

**Comment by akorchev** [comment]
Radzen Blazor Studio should now automatically restart the application in such cases.
