### ISSUE TITLE
Class generation error when infering SQLdatabase

### ISSUE THREAD

**Issue by hampusWisest** [radzenhq/radzen-blazor-studio#47]
When connecting to a database with a  "**-**"    in the name, the Serviceclass generated with that name will not work due to the "**-**" is not allowed in a class name.

Test done with a database named **test-database**.
![image](https://user-images.githubusercontent.com/63351366/174753990-7ef50422-2593-440a-85d0-2be62ae76bae.png)

The generated service class anme will be as shown on the screenshot:
![image](https://user-images.githubusercontent.com/63351366/174755264-c773272d-4949-413a-9463-3faba6d4b20b.png)

How to fix:
When a database name contains a "**-**" replace the generated names with an "**_**".
![image](https://user-images.githubusercontent.com/63351366/174755667-395db52d-4231-410d-9024-c1292a87dd56.png)

**Comment by akorchev** [comment]
Thank you for reporting this problem @hampusWisest! We will add validation to this field so it doesn't allow invalid names.
