### ISSUE TITLE
Minor UI Defect: subfolder collapses on file selection

### ISSUE THREAD

**Issue by meaderick** [radzenhq/radzen-blazor-studio#51]
Version: 1.0.0-alpha.5
![image](https://user-images.githubusercontent.com/3912375/178044058-ddae5bcd-fc15-43f1-8f8b-d8e56546c589.png)

Open project, expand a folder (in my case with a single file under it), then select _any_ file.

The subfolder node collapses and the file is not shown. Requires two clicks to see again. Does not seem to happen with top level folders, just subfolders.

Video demo attached.

https://user-images.githubusercontent.com/3912375/178044083-51d1af7f-0409-412c-ab66-7e357add1f8c.mp4

**Comment by akorchev** [comment]
Hi @meaderick,

Thank you for reporting this issue. It should be addressed by the new RBS release - alpha.6.

**Comment by meaderick** [comment]
Confirmed that this is fixed in 1.0.0-alpha.6. Closing the issue.

Thanks @akorchev
