### ISSUE TITLE
The context menu is not working properly on the project tree.

### ISSUE THREAD

**Issue by koksalbasar** [radzenhq/radzen-blazor-studio#53]
Radzen Blazor Studio Version : alpha.7

1. The project tree doesn't refresh after new comments (**New Directory, New File** or **New Page**). Must reload the project to see the new item.
2. Find file search box is working well. When searching the new item's name on the search box, the project tree is refreshing correctly and it opens the file on the editor screen before reloading the project. New directories can't show in this operation because the searching function is working for the files.
3. When creating a new page the editor screen can't show the created page if the search box is used for the first time. Reloading the project is working sometimes. Reopen the Radzen Blazor Studio is working always.
4. New pages created in the subdirectory under the Pages directory can't be shown. 
5. **The Delete comment** is working but can't refresh the project tree with some conditions. If the files are selected from the search box the project tree can't be refreshing. When the *.razor files are deleted the project tree can't refresh in any condition (main list or created from the search box)

**Comment by koksalbasar** [comment]
> 4\. New pages created in the subdirectory under the Pages directory can't be shown.

Update : CRUD Pages not working. Empty and Data Grid with Form are worked.

**Comment by akorchev** [comment]
Hi @koksalbasar,

We released a new update today which should address some of those issue. Please let us know if it works for you. If not - we would appreciate more detailed steps that will allow us how to reproduce the issue(s).

**Comment by koksalbasar** [comment]
Hi @akorchev,

The issues that I reported seem solved.

Thank you for your efforts.

PS: I have a little suggestion. This is not an issue.

- XXX.razor
- XXX.razor.designer.cs
- XXX.razor.cs

These files are working together. Maybe you can plan that these files can delete together.

**Comment by akorchev** [comment]
We plan to introduce a so called "simple" or "logical" view of the app when there won't be any files but "pages" (similar to current Radzen 2.x). This would allow you to delete everything at once. 

We also think of introducing "grouping" of files (similar to what Visual Studio does).

**Comment by koksalbasar** [comment]
Seems so nice.

This issue is closed :)
