### ISSUE TITLE
Compile-time warnings hide the compile errors

### ISSUE THREAD

**Issue by BlazorSaddles** [radzenhq/radzen-blazor-studio#55]
During compile, my application has many **warning** messages which make it difficult  to find the real **errors** that are generated.   

It would would help if the warning messages could be turned on/off or the errors could be highlighted, i.e. color them red.

**Comment by akorchev** [comment]
You can hide the warnings you don't want to see in the csproj file. Something like this:

```
 <NoWarn>BL9993</NoWarn>
 ```
