### ISSUE TITLE
Build errors not written to log

### ISSUE THREAD

**Issue by BlazorSaddles** [radzenhq/radzen-blazor-studio#56]
Build errors aren't written to the log.txt file, which makes it hard to copy/paste.  This means we have to manually type in the errors when reporting them.

**Comment by akorchev** [comment]
You should be able to select, and copy the content of the output pane (via ctrl+c). Doesn't this work? Screenshot attachments also work.

**Comment by BlazorSaddles** [comment]
Sorry, I only tried right-click to copy, rather than ctrl+c.  The ctrl+c works fine.
