### ISSUE TITLE
CRUD fails for MSSQL views

### ISSUE THREAD

**Issue by peterbeery** [radzenhq/radzen-blazor-studio#58]
I get a run time error at launch when my database has a view and I've told Radzen to create CRUD pages.  I need a way to turn off just a portion of CRUD functions for just the views while keeping them for tables. I.e. keep READ but suppress CREATE, etc.

**Comment by akorchev** [comment]
> I get a run time error at launch when my database has a view and I've told Radzen to create CRUD pages
Can you elaborate?

>  I need a way to turn off CRUD pages for just the views while keeping them for tables

This should already be possible by unchecking the Views.

<img width="349" alt="image" src="https://user-images.githubusercontent.com/454726/190577048-d32b85e6-c705-4af9-a4d3-423a281c94e6.png">

**Comment by peterbeery** [comment]
Thanks for the quick reply. Sorry I didn't give enough detail.  Basically, the view is named something like vwClientDetails.  It's essentially a join across two tables.  CRUD on single table views make absolute sense. But once you join more than one table, only a subset of CRUD makes logical sense.  Read should work. Update could be made to work, and maybe even delete if your cascading delete  process is clever enough. But INSERT on a multi-table view is problematic.  The view may only see a subset of the columns. Some of the missing columns may be required fields in the source table. The INSERT on view option wouldn't know what values to put them those columns.   By the way, I think this same issue exists in the other version of Radzen 2.x.   We need a way to only have a subset of CRUD options in play for multi-table views.

Here is the runtime error that I get. As you can see it doesn't like UpdateVwClientDetails. (sorry about the black background, this alpha tool spontaneously flips to it no matter what choice I select in settings.) 
![Screenshot 2022-09-16 082832](https://user-images.githubusercontent.com/61803429/190650330-2f6f3256-a363-4e78-a27f-026d2c17c16f.png)

**Comment by akorchev** [comment]
You can uncheck individual views at the moment. Ability to select what page to scaffold is not yet available.
