### ISSUE TITLE
The notification severity list has the wrong key

### ISSUE THREAD

**Issue by koksalbasar** [radzenhq/radzen-blazor-studio#62]
The notification severity list has the wrong key

While adding a notify In the methods design screen severity dropdown box has Danger key instead of Error.

![Severity](https://user-images.githubusercontent.com/56689928/193627420-0dd7d45f-ccc5-4b2a-91dc-ae411ae16494.png)

**Comment by akorchev** [comment]
Hi @koksalbasar,

Just released beta.1 which should solve this issue. Thank you for reporting it!

**Comment by koksalbasar** [comment]
It works. Thank you
