### ISSUE TITLE
[Feature request] Some additional functions for the Methods design screen

### ISSUE THREAD

**Issue by koksalbasar** [radzenhq/radzen-blazor-studio#63]
If somebody chose to use the methods design screen that means she/he doesn't want to use the code screen very often. But in this development stage of the Radzen Blazor Studio, there is no seamless experience for the developer.

I think the following functionalities must be added.

+ Collapse and expand blocks
+ Move blocks between nodes (plus signs)
   + (and / or ) Cut, copy, paste blocks
+ Link to an invoked method if it's possible. This could be done as a popup or a new screen. If the new screen appears a back button will be useful.

**Comment by koksalbasar** [comment]
Hi,

The beta.2 brings many improvements. The designer is much much more usable now. But the lines are disappearing in the down places. 


![image](https://user-images.githubusercontent.com/56689928/199339585-e089c768-7275-4c78-9ce8-d8a337fbdbb8.png)

**Comment by akorchev** [comment]
Hi @koksalbasar, 

We discovered this issue shortly after making the beta 2 release. We will address it with the next one.
