### ISSUE TITLE
The page name property is missing for new pages except for the Empty template.

### ISSUE THREAD

**Issue by koksalbasar** [radzenhq/radzen-blazor-studio#66]
User can select the page name only if she/he creates an empty page.  RBS is pushing the static name that is created from the entity name for all other templates. Naming is one of the good options in Radzen.

In addition, a rename functionality is needed on the project explorer.

**Comment by akorchev** [comment]
> User can select the page name only if she/he creates an empty page. RBS is pushing the static name that is created from the entity name for all other templates. Naming is one of the good options in Radzen.

I am afraid I don't understand this.

> In addition, a rename functionality is needed on the project explorer.

We will add this at some point.

**Comment by koksalbasar** [comment]
A user can give the page name if she/he creates a page as an Empty page.
![pageName0](https://user-images.githubusercontent.com/56689928/193819012-31f58124-048c-4b2b-90e3-c51e7f0b6ed0.png)
![pageName](https://user-images.githubusercontent.com/56689928/193819080-03ac8379-6145-450b-90dc-c33e75c47f38.png)

In other cases have not Page name.
![pageName1](https://user-images.githubusercontent.com/56689928/193819989-f274e1bf-ebfe-43b3-830f-a5e8e48b92ba.png)

Users can use the "Include in main navigation" property for each option but can give it only if the page is empty.

**Comment by akorchev** [comment]
The CRUD templates generate multiple pages that have different names - Add XXX, Edit XXX etc. This is why specifying a name is not available.

**Comment by koksalbasar** [comment]
But the same functionality is already available current Radzen and it's useful option if the programmer has own naming strategy.

For example I'm using special prefix for the pages. Ofcourse this is not deatly.

**Comment by akorchev** [comment]
> But the same functionality is already available current Radzen and it's useful option if the programmer has own naming strategy.

Radzen's new CRUD page allows you to create **one** page. RBS allows you to create **many** pages. You can't use a single textbox to specify the name of many pages.

**Comment by koksalbasar** [comment]
Hi @akorchev,

I think we are looking from different windows. For this, I couldn't explain what I mean. 

Radzen creates **3 files already**. 
FileName.Razor
FileName.Razor.cs
FileName.Razor.designer.cs
When I set a file name Radzen uses this file name (from the only one text box) and creates all other file names (Add_ and Edit_ things).

I'm not asking more than this. I'm used to giving some different kinds of prefixes for the files. app, sys, adm, etc. As I said before this is not deathly. 

But I can suggest something for your Add and Edit prefixes. If a developer can select these extensions as a prefix or suffix will be very useful. Because in your case, groups are (pages one after another) functional. Main pages, add pages and edit pages. But if these extensions become suffixes in this case pages create their own groups. This may be easy (and more systematic) for huge projects. (Search box is a good option but not the same that I want to explain)

**Comment by akorchev** [comment]
I am leaving this open but we don't plan to act on it any time soon due to other higher priority tasks.

**Comment by koksalbasar** [comment]
Fair enough. because I think nobody asked but me.

I still use my naming strategy with renaming pages and class names. It's not what I expected (doing something outside of the tool) when I use a RAD software but I agree with your opinion this is not a high priority. I hope you can find time to add this feature in the future.

**Comment by akorchev** [comment]
This is now possible with 1.22.0.
![set-page-name](https://github.com/radzenhq/radzen-blazor-studio/assets/454726/c2dfc017-cded-46a7-9bd5-40b29da51298)
