### ISSUE TITLE
Minor UI defect combo box does not sort the values

### ISSUE THREAD

**Issue by kurtkluth** [radzenhq/radzen-blazor-studio#67]
The database combo box does not sort the database names on the MSSQL connection screen as shown below:

![DatabaseCombo](https://user-images.githubusercontent.com/24981524/194209951-f01d4428-659c-4d9a-bce4-a83a794d54ed.jpg)

**Comment by akorchev** [comment]
Thanks @kurtkluth we will make it sort in the next release.
