### ISSUE TITLE
Loading available templates, nothing happens

### ISSUE THREAD

**Issue by researchmaster** [radzenhq/radzen-blazor-studio#69]
When I go to create a new application it says loading available templates and just sits on this screen.

**Comment by akorchev** [comment]
Hi @researchmaster,

Do you have .net 6 installed? It is required by Radzen Blazor Studio.

**Comment by researchmaster** [comment]
Thank You,

I had 6 installed but you needed the SDK version.

Ron

**Comment by akorchev** [comment]
Radzen Blazor Studio now needs .NET7 SDK and should check for its presence and notify you if not found.
