### ISSUE TITLE
Page threw exception

### ISSUE THREAD

**Issue by mdchafin** [radzenhq/radzen-blazor-studio#7]
C:\Development\Git\PCT\Web\PCT\Components\RecipientGrid.razor(2844,3992): error CS7036: There is no argument given that corresponds to the required formal parameter 'node' of 'Discount.Discount(NodeWrapper)'
C:\Development\Git\PCT\Web\PCT\Components\RecipientGrid.razor(2844,4363): error CS7036: There is no argument given that corresponds to the required formal parameter 'node' of 'AddOn.AddOn(NodeWrapper)'
C:\Development\Git\PCT\Web\PCT\Components\RecipientGrid.razor(2844,9563): error CS7036: There is no argument given that corresponds to the required formal parameter 'node' of 'Discount.Discount(NodeWrapper)'
C:\Development\Git\PCT\Web\PCT\Components\RecipientGrid.razor(2844,9934): error CS7036: There is no argument given that corresponds to the required formal parameter 'node' of 'AddOn.AddOn(NodeWrapper)'
C:\Development\Git\PCT\Web\PCT\Components\RecipientGrid.razor(2847,3920): error CS7036: There is no argument given that corresponds to the required formal parameter 'node' of 'Discount.Discount(NodeWrapper)'
C:\Development\Git\PCT\Web\PCT\Components\RecipientGrid.razor(2847,4291): error CS7036: There is no argument given that corresponds to the required formal parameter 'node' of 'AddOn.AddOn(NodeWrapper)'
C:\Development\Git\PCT\Web\PCT\Components\RecipientGrid.razor(2847,9491): error CS7036: There is no argument given that corresponds to the required formal parameter 'node' of 'Discount.Discount(NodeWrapper)'
C:\Development\Git\PCT\Web\PCT\Components\RecipientGrid.razor(2847,9862): error CS7036: There is no argument given that corresponds to the required formal parameter 'node' of 'AddOn.AddOn(NodeWrapper)'
C:\Development\Git\PCT\Web\PCT\Components\RecipientGrid.razor(2849,5164): error CS7036: There is no argument given that corresponds to the required formal parameter 'node' of 'Discount.Discount(NodeWrapper)'
C:\Development\Git\PCT\Web\PCT\Components\RecipientGrid.razor(2849,5535): error CS7036: There is no argument given that corresponds to the required formal parameter 'node' of 'AddOn.AddOn(NodeWrapper)'
C:\Development\Git\PCT\Web\PCT\Components\RecipientGrid.razor(2849,8763): error CS7036: There is no argument given that corresponds to the required formal parameter 'node' of 'Discount.Discount(NodeWrapper)'
C:\Development\Git\PCT\Web\PCT\Components\RecipientGrid.razor(2849,9134): error CS7036: There is no argument given that corresponds to the required formal parameter 'node' of 'AddOn.AddOn(NodeWrapper)'

   at Radzen.Server.ProjectContext.Compile(Compilation compilation, AssemblyLoadContext context) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectContext.cs:line 120
   at Radzen.Server.ProjectServer.Compile(String fileName, String source, RazorProjectEngine projectEngine) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 778
   at Radzen.Server.ProjectServer.CompilePage(String fileName, String source, RazorProjectEngine engine) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 328
   at Radzen.Server.ProjectServer.Render(String fileName, String source) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 397
   at Radzen.Server.ProgramController.Render(RenderRequest request) in /Users/korchev/github/radzen-next/Radzen.Server/ProgramController.cs:line 305

**Comment by akorchev** [comment]
We would need access to the actual app if possible in order to troubleshoot.

**Comment by Saadi-92** [comment]
Same here ... When I opened an existing application only issue I faced it is not rendering the pages, but ist running the application fine

**Comment by akorchev** [comment]
@Saadi-92 can you share your application with us (you can send it to info@radzen.com)? We would like to investigate further.

**Comment by mdchafin** [comment]
The application is private at this time. Sorry but there is nothing unique about it.

**Comment by akorchev** [comment]
@Saadi-92 I was able to open your application with the latest version we just released (1.0.0.preview.5). Some pages stay empty in design mode though which we will investigate further!

**Comment by Saadi-92** [comment]
Great, thanks for the update!



Muhammad Saeed Shaikh
Senior Analyst/Team Lead, PO&IT BDF
+97333196962
| https://bh.linkedin.com/in/saadi92
***@***.***
| RIFFA, Kingdom of Bahrain <https://maps.google.com/?q=RIFFA, Kingdom of
Bahrain>
| ***@***.***
<https://www.facebook.com/Saadi92>
<https://www.facebook.com/saeedsaadipoetry/>
<https://www.linkedin.com/in/saadi92/> <https://twitter.com/M_Saeed_A>
<https://www.instagram.com/saadi92a/>
<https://www.youtube.com/channel/UCHuJZG6oKfQVUP_C7i9fFKQ>
<http://saadi-online.blogspot.com/>
[image: Green] Please consider your environmental responsibility. Before
printing this e-mail message, ask yourself whether you really need a hard
copy.

"Truth, Honesty, Legacy Some are born great, some achieve greatness, and
some have greatness thrust upon them." - William Shakespeare
[image: App Youtube Status Image]
<https://www.youtube.com/watch?v=LJxmkldcGFM>
[image: App Youtube Status Image]YouTube Video
[image: App Social Buttons Image] <https://bh.linkedin.com/in/saadi92>

Create your own email signature
<https://www.wisestamp.com/create-own-signature/?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own&srcid=>

**Comment by akorchev** [comment]
The problem reported in @Saadi-92 's app seems to be fixed. The original issue requires additional context though - the class Discount seems to be app specific.
