### ISSUE TITLE
Exception at Humanizer.Inflections.Vocabulary.MatchUpperCase when database model is discovered

### ISSUE THREAD

**Issue by miquelalcaraz** [radzenhq/radzen-blazor-studio#71]
If we want generate code for a Database that has a field named [S], after choose the connection [MSSQL connection] we found the exception: 
`
Index was outside the bounds of the array.
at Humanizer.Inflections.Vocabulary.MatchUpperCase ...
`

To reproduce, only need to create a new database with one table and [S] field, then connect Db with radzen studio.

`CREATE DATABASE [localstg001]
GO

CREATE TABLE [localstg001].[dbo].[Test](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[S] [INT] NOT NULL  
) 
GO
`
Notes: 
- Environment: Radzen Blazor Studio 1.0.1 + .Net Core 7.0
- Doesn't happen with beta versions.
- Doesn't happen for fields with names like [N] or [X]

**Comment by enchev** [comment]
Fixed and the fix will be part of our next update!
