### ISSUE TITLE
15 day Trail  still creates dummy data application.

### ISSUE THREAD

**Issue by ocoguz** [radzenhq/radzen-blazor-studio#73]
I can not choose my database , some data coming and very slow. Cant I choose my MS sql server Oracle MySQL on my local?

**Comment by akorchev** [comment]
Hi @ocoguz,

Radzen Blazor Studio should allow you to choose your own database - in fact there is no other way to add a database connection.

 It [displays sample data in design-time](https://www.radzen.com/blazor-studio/documentation/troubleshooting/#code-in-lifecycle-methods-does-not-execute-in-design-time) by default.
