### ISSUE TITLE
Cannt run Radzen project if ref project Sdk="Microsoft.NET.Sdk.Web"

### ISSUE THREAD

**Issue by sergpy** [radzenhq/radzen-blazor-studio#74]
I cannot run opened project in Radzen Blazor Studio, if referenced project.csproj has settings Sdk="Microsoft.NET.Sdk.Web"
if Project Sdk ="Microsoft.NET.Sdk" all ok

My Output log:

dotnet watch 🚀 Started
dotnet watch ⌚ Exited
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...

**Comment by akorchev** [comment]
At the moment Radzen picks the first "web" project to run (based on the SDK). We will look for a way to pick a different project to start.

**Comment by akorchev** [comment]
Recent versions have the option to set a startup project from the project context menu.
