### ISSUE TITLE
Method designer doesn't work for some DropDown events.

### ISSUE THREAD

**Issue by koksalbasar** [radzenhq/radzen-blazor-studio#77]
Hi Guys,

When I try to create or add a method to the **RadzenDropDown** component's **SelectedItemChanged** event, RBS generates the following error.

Notes : 
* I played TValue but nothing changed.
* I also tried to add this method to razor file manually. But it didn't work.

```
C:\Users\Administrator\source\repos\Valura_v2\server\Pages\Tenant.razor(101,278): error CS0407: Task TenantComponent.cmbCityChange(object)' has wrong return type
C:\Users\Administrator\source\repos\Valura_v2\server\Pages\Tenant.razor(322,175): error CS1662: Unable to convert lambda expression to requested delegate type because some of the return types in the block are not implicitly convertible to delegate return type
   at Radzen.Server.ProjectContext.Compile(Compilation compilation, AssemblyLoadContext context) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectContext.cs:line 173
   at Radzen.Server.ProjectContext.Compile(Compilation compilation) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectContext.cs:line 178
   at Radzen.Server.ProjectServer.Compile(String fileName, String source, RazorProjectEngine projectEngine) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 1095
   at Radzen.Server.ProjectServer.CompilePage(String fileName, String source, RazorProjectEngine engine) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 451
   at Radzen.Server.ProjectServer.Render(String fileName, String source) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 706
   at Radzen.Server.ProgramController.Render(RenderRequest request) in /Users/korchev/github/radzen-next/Radzen.Server/ProgramController.cs:line 454
<RadzenDropDown TValue="string" Style="width: 100%" Data="@Globals.cities" TextProperty="CityName" ValueProperty="GeoNameId" SelectedItem="@selectedCity" @bind-Value="@selectedCity.GeoNameId" Name="cmbCity" Change="@cmbCityChange"></RadzenDropDown>, 1 of 2 found for 'cmbcity', at 101:223
```

**ValueChanged event also causes the error.**

---

In addition, some events can not show the method name on the Method Designer when it's created. 

For example;
When selecting RadzenDropDown ContextMenu from the Event tab, the Method Designer shows the method name on the designer Combobox.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/56689928/204289905-7171e517-a7e6-4487-aa08-9ea242c3b851.png">

But when selecting RadzenTextBox Change event the Method Designer doesn't show the name, but the method name is still there (CityNameChange in this example). This is not causing an error. The developer can continue with selecting the correct method name.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/56689928/204292077-c8957f5f-6e2f-499f-be69-e9d9b71dda79.png">

**Comment by akorchev** [comment]
Hi @koksalbasar,

We will handle the DropDown event issues with the next release.

I can't understand the second issue about RadzenTextBox change event.

**Comment by koksalbasar** [comment]
The second issue is not an error. But the developer can be confused when she/he tries to select the method name.

I'll try to explain. 
Please follow the steps to regenerate the issue.

**A) Normal process :**
---
1) Select the ContextMenu event from the RadzenDropDown component's Event tab and click the + sign.
![image](https://user-images.githubusercontent.com/56689928/204381765-b0d38c5f-b106-4e75-a0e0-a95ab217c6af.png)

2) Select the code page, give the name and click the OK button
![image](https://user-images.githubusercontent.com/56689928/204381794-ef6e317e-642a-4964-9112-9d8b73c1e4e7.png)

3) RBS creates the method and selects the method name from the designer page.
![image](https://user-images.githubusercontent.com/56689928/204381827-6d9d212b-aa6f-4e04-9d59-0986aa96a609.png)

**B) The process with issue :**
---
1) Select the Change event from the RadzenTextBox component's Event Tab and click the + sign.
![image](https://user-images.githubusercontent.com/56689928/204381911-2bf7ebd6-d9fd-48d7-b615-2579a1699fc5.png)

2) Select the code page, give the name and click the OK button
![image](https://user-images.githubusercontent.com/56689928/204381930-37bc29df-c840-4a4b-b4ea-aee86b6bed29.png)

3) RBS creates the method but does not select the method name from the designer page.
![image](https://user-images.githubusercontent.com/56689928/204381956-c49c1bc1-46e2-482c-9b85-a24b0202fa38.png)

4) The method is already added to the method list.
![image](https://user-images.githubusercontent.com/56689928/204381990-6926fc0e-0ffa-45f7-864b-fb57bc7d87a0.png)


As I said in the beginning this is not caused by an error but is confusing.

**Comment by koksalbasar** [comment]
Hi @akorchev,
SelectedItemChanged@_RadzenDropDown_ --> **Solved**
ValueChanged@_RadzenDropDown_ --> **Solved**
Change@_RadzenTextBox_ --> **Solved**

This issue is solved and closed
