### ISSUE TITLE
RBS cannot build project

### ISSUE THREAD

**Issue by hrvoje-grabusic** [radzenhq/radzen-blazor-studio#83]
Hi,

My project builds fine in visual studio but not in RBS.
Not sure what i am doing wrong.

I have those usings defined in GlobalUsings.cs

Here is the analyze log.
> Analyzing D:\Work\test\WebUI\WebUI.csproj ...
>     Analyzing D:\Work\test\AppDomain\Domain.csproj ...
>     Done.
>     Analyzing D:\Work\test\AppServices\AppServices.csproj ...
>     Done.
>     Analyzing D:\Work\test\WebUI\WebUI.csproj ...
>         Rendering Pages\Counter.razor ... OK.
>         Rendering Pages\Index.razor ... OK.
>         Rendering Pages\ProductDatabases.razor ... FAIL.
>             Radzen.Server.CompilationFailedException: D:\Work\test\WebUI\Pages\ProductDatabases.razor(16,7): error CS0246: The type or namespace name 'ProductDatabase' could not be found (are you missing a using directive or an assembly reference?)
>             D:\Work\test\WebUI\Pages\ProductDatabases.razor(159,75): error CS0246: The type or namespace name 'ProductDatabaseManager' could not be found (are you missing a using directive or an assembly reference?)
>             D:\Work\test\WebUI\Pages\ProductDatabases.razor(16,55): error CS0246: The type or namespace name 'ProductDatabase' could not be found (are you missing a using directive or an assembly reference?)
>             D:\Work\test\WebUI\Pages\ProductDatabases.razor(164,74): error CS0246: The type or namespace name 'ProductDatabase' could not be found (are you missing a using directive or an assembly reference?)
> 
>                at Radzen.Server.ProjectContext.Compile(Compilation compilation, AssemblyLoadContext context) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectContext.cs:line 154
>                at Radzen.Server.ProjectContext.Compile(Compilation compilation) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectContext.cs:line 178
>                at Radzen.Server.ProjectServer.Compile(String fileName, String source, RazorProjectEngine projectEngine) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 1280
>                at Radzen.Server.ProjectServer.CompilePage(String fileName, String source, RazorProjectEngine engine) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 552
>                at Radzen.Server.ProjectServer.Crawl(String fileName, String source) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 856
>                at Radzen.Server.ProjectAnalyzer.AnalyzeFile(ProjectContext projectContext, SolutionFacade solutionFacade, String razorFile, Boolean parallel, Boolean all, CancellationToken token) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectAnalyzer.cs:line 122
>         Rendering Pages\Products.razor ... OK.
>         Rendering Shared\MainLayout.razor ... OK.
>     Done.
> Finished with errors.

After adding the using directly into the problem file i get a different error.
> system.NotSupportedException: A non-collectible assembly may not reference a collectible assembly.

> Analyzing D:\Work\test\WebUI\WebUI.csproj ...
>     Analyzing D:\Work\test\AppDomain\Domain.csproj ...
>     Done.
>     Analyzing D:\Work\test\AppServices\AppServices.csproj ...
>     Done.
>     Analyzing D:\Work\test\WebUI\WebUI.csproj ...
>         Rendering Pages\Counter.razor ... OK.
>         Rendering Pages\Index.razor ... OK.
>         Rendering Pages\ProductDatabases.razor ... FAIL.
>             System.NotSupportedException: A non-collectible assembly may not reference a collectible assembly.
>                at System.Reflection.Emit.ModuleBuilder.GetTypeRefNested(Type type, Module refedModule)
>                at System.Reflection.Emit.ModuleBuilder.GetTypeTokenWorkerNoLock(Type type, Boolean getGenericDefinition)
>                at System.Reflection.Emit.ModuleBuilder.GetTypeTokenInternal(Type type, Boolean getGenericDefinition)
>                at System.Reflection.Emit.TypeBuilder..ctor(String fullname, TypeAttributes attr, Type parent, Type[] interfaces, ModuleBuilder module, PackingSize iPackingSize, Int32 iTypeSize, TypeBuilder enclosingType)
>                at System.Reflection.Emit.ModuleBuilder.DefineType(String name, TypeAttributes attr, Type parent, Type[] interfaces)
>                at Microsoft.AspNetCore.SignalR.Internal.TypedClientBuilder`1.GenerateInterfaceImplementation(ModuleBuilder moduleBuilder)
>                at Microsoft.AspNetCore.SignalR.Internal.TypedClientBuilder`1.GenerateClientBuilder()
>                at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
>                at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
>                at System.Lazy`1.CreateValue()
>                at Microsoft.AspNetCore.SignalR.Internal.TypedClientBuilder`1.Build(IClientProxy proxy)
>                at Microsoft.AspNetCore.SignalR.Internal.HubClients`2..ctor(HubLifetimeManager`1 lifetimeManager)
>                at Microsoft.AspNetCore.SignalR.Internal.HubContext`2..ctor(HubLifetimeManager`1 lifetimeManager)
>                at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
>                at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
>                at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>                at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
>                at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
>                at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
>                at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
>                at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
>                at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
>                at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
>                at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
>                at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
>                at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
>                at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
>                at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
>                at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
>                at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
>                at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>                at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
>                at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass7_0.<CreateInitializer>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
>                at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
>                at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
>                at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
>                at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
>                at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
>                at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
>                at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
>                at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
>                at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
>                at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
>             --- End of stack trace from previous location ---
>                at Radzen.Server.HtmlRenderer.HandleException(Exception exception) in /Users/korchev/github/radzen-next/Radzen.Server/HtmlRenderer.cs:line 71
>                at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
>                at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
>                at Radzen.Server.Router.Render(Type layout, Type component) in /Users/korchev/github/radzen-next/Radzen.Server/Router.cs:line 98
>                at Radzen.Server.StaticRouter.SetParametersAsync(ParameterView parameters) in /Users/korchev/github/radzen-next/Radzen.Server/Router.cs:line 40
>                at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
>             --- End of stack trace from previous location ---
>                at Radzen.Server.HtmlRenderer.HandleException(Exception exception) in /Users/korchev/github/radzen-next/Radzen.Server/HtmlRenderer.cs:line 71
>                at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
>                at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters)
>                at Radzen.Server.HtmlRenderer.CreateInitialRenderAsync(Type componentType, ParameterView initialParameters) in /Users/korchev/github/radzen-next/Radzen.Server/HtmlRenderer.cs:line 262
>                at Radzen.Server.HtmlRenderer.RenderComponentAsync(Type componentType, ParameterView initialParameters) in /Users/korchev/github/radzen-next/Radzen.Server/HtmlRenderer.cs:line 57
>                at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c__11`1.<<InvokeAsync>b__11_0>d.MoveNext()
>             --- End of stack trace from previous location ---
>                at Radzen.Server.ProjectServer.Crawl(String fileName, String source) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 873
>                at Radzen.Server.ProjectAnalyzer.AnalyzeFile(ProjectContext projectContext, SolutionFacade solutionFacade, String razorFile, Boolean parallel, Boolean all, CancellationToken token) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectAnalyzer.cs:line 122
>         Rendering Pages\Products.razor ... OK.
>         Rendering Shared\MainLayout.razor ... OK.
>     Done.
> Finished with errors.

**Comment by hrvoje-grabusic** [comment]
Sent

**Comment by akorchev** [comment]
Thank you @hrvoje-grabusic. We reproduced the problem and will release a fix for it with the next release.

**Comment by hrvoje-grabusic** [comment]
I updated RBS and the building now works for my project if i leave the using statements in the razor page file.

If i take out the using statements from the page and leave them only in GlobalUsings.cs that still doesn't work in RBS but it does work in visual studio.
Now it show the error in RBS which i nice. No need to run the analyzer.
> The type or namespace name 'ProductDatabase' could not be found (are you missing a using directive or an assembly reference?)

If i add the using statements in the _imports.razor then it works in RBS also.

**Comment by hrvoje-grabusic** [comment]
From the ProductDatabases.razor remove the lines.
> @using AppServices.Services.Data
> @using Domain.Data.Products

This is the only change.
This will build in viusal studio and works but not in RBS.

It seems razor supports using statements in both GlobalUsings.cs and _imports.razor.
While RBS ignores GlobalUsings.cs
