### ISSUE TITLE
Changes are not saved

### ISSUE THREAD

**Issue by Alex1019710211** [radzenhq/radzen-blazor-studio#88]
When you finish working with Radzen Blazor Studio using the close window button (top right), the changes made are not saved, and the user is not warned about this in any way. At the same time, when using the File --> Close Editor menu item, it works. But more often, users use the window close button to close the window (by analogy with Visual Studio).

**Comment by bconte-mh** [comment]
I have been experiencing this with the current version as well (1.9.7)

**Comment by akorchev** [comment]
Should be supported since 1.9.8.
