### ISSUE TITLE
Roles not visible when Setting Page Properties

### ISSUE THREAD

**Issue by TheKanky** [radzenhq/radzen-blazor-studio#91]
I am trying to set my page access to Authenticated. 

When I try select a role from the drop down I see "Failed to get roles". When I try the refresh button there is no change. 

I have added role from the page when logged in as admin/admin. 

My page has `@attribute [Authorize]`. When I try to demo the app on IIS I cannot get past the login page, as I suspect the access roles are not set. 

Is this a bug in the software, or do I need to set the role access in code only?

**Comment by akorchev** [comment]
Hi @TheKanky,

This is definitely not a known issue. The dropdown with roles should fetch them from the database via the AspNetRoles table. Here is how it is supposed to look:

<img width="287" alt="image" src="https://user-images.githubusercontent.com/454726/212894163-5b0de13c-dd23-4c2b-9f03-5f4682a86441.png">

Can you provide more info about your application?

1. Is it an existing one or a new one created with Radzen Blazor Studio?
2. What .NET version is it using?
3. Is it Blazor server or WASM?
4. What database is it using?
5. Can you confirm the database has the AspNetRoles table and it contains the desired records?

**Comment by TheKanky** [comment]
Hi @akorchev 

Thanks for the reply. 

1. This is a new project created with Radzen Blazor Studio.
2. We are targeting Net7
3.  It is a Blazor Server app.
4. Connecting to MySql.
5.

`CREATE TABLE `AspNetRoles` (
  `Id` varchar(255) NOT NULL,
  `ConcurrencyStamp` longtext,
  `Name` varchar(256) DEFAULT NULL,
  `NormalizedName` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE KEY `RoleNameIndex` (`NormalizedName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`

![image](https://user-images.githubusercontent.com/31211651/212895645-3e58d012-08a0-4b5c-95ce-d118734af7b3.png)

**Comment by akorchev** [comment]
It seems there is a problem specific to MySQL databases. We will address it with the next release.

**Comment by akorchev** [comment]
Hi @TheKanky,

I am closing this issue as it should be fixed in latest versions.
