### ISSUE TITLE
Subscription Message Error in Bazor Studio 

### ISSUE THREAD

**Issue by BillEisenman** [radzenhq/radzen-blazor-studio#93]
I've just purchased a Radzen Blazor Studio Professional Subscription. After I enter the License Key, why does the Dialog show that  my subscription ends on 2/19/ 2023 when I purchased on this date? Shouldn't it say 2/19/2024?

**Comment by akorchev** [comment]
I have replied over email but will post it here too:

This seem to be some timezone related issue. Radzen Blazor Studio displays wrong end date if the purchase is "from the future". We will investigate what is causing this problem and try to fix it with the next release.

The license dialog should display the correct end date after a few hours.

**Comment by akorchev** [comment]
Should be addressed since 1.4.0.
