### ISSUE TITLE
"Error writting to XML documenation file" when open a new razor file

### ISSUE THREAD

**Issue by fl0wm0ti0n** [radzenhq/radzen-blazor-studio#95]
![image](https://user-images.githubusercontent.com/24993288/221371567-e9f5415c-8f1b-4c89-b2b4-c9447dd99c0f.png)

**Comment by akorchev** [comment]
This is probably also caused by Radzen Blazor Studio not supporting MAUI projects.

**Comment by akorchev** [comment]
We have fixed a similar issue in more recent releases.
