### ISSUE TITLE
Allow RBS user to set the local date format for their region

### ISSUE THREAD

**Issue by 274188A** [radzenhq/radzen-blazor-studio#98]
Allow RBS user to set the local date format for their region.

This would save them having to change  the default repeatedly when code generating.

![image](https://github.com/radzenhq/radzen-blazor-studio/assets/40014477/b25f976a-7047-41a4-ae07-6a1e62659bdf)

**Comment by chlupac** [comment]
please persist settings in this dialog

**Comment by akorchev** [comment]
There is now an option to set the default date format for all applications (you need 1.22.0 or newer). It is available from the settings screen in the bottom left corner.
![template-settings](https://github.com/radzenhq/radzen-blazor-studio/assets/454726/5ab50797-b722-467b-ac7d-36621819e45b)
